---
name: add_delete_branch_worker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102208
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381640
milestone: '15.6'
type: development
group: group::code review
default_enabled: false
