---
name: admin_mode_for_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107925
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/387729
milestone: '15.8'
type: development
group: group::authentication and authorization
default_enabled: false
