---
name: batched_migrations_parallel_execution
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104027
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/384883
milestone: '15.7'
type: development
group: group::database
default_enabled: false
