---
name: check_ip_address_for_email_verification
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106441
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385196
milestone: "15.7"
type: development
group: group::anti-abuse
default_enabled: false
