---
name: ci_enforce_rate_limits_jobs_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104912
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/384186
milestone: '15.7'
type: development
group: group::pipeline execution
default_enabled: false
