---
name: ci_hooks_pre_get_sources_script
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102332
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381840
milestone: '15.6'
type: development
group: group::pipeline authoring
default_enabled: false
