---
name: counter_attribute_db_lease_for_update
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97912
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/374596
milestone: '15.5'
type: development
group: group::pipeline insights
default_enabled: false
