---
name: create_runner_workflow
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109497
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/389269
milestone: '15.9'
type: development
group: group::runner
default_enabled: false
