---
name: environment_details_vue
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105527"
rollout_issue_url: "https://gitlab.com/gitlab-org/gitlab/-/issues/384914"
milestone: '15.7'
type: development
group: group::release
default_enabled: false
