---
name: fork_divergence_counts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103814
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/382878
milestone: '15.7'
type: development
group: group::source code
default_enabled: false
