---
name: frontend_caching
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106004
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386275
milestone: '15.7'
type: development
group: group::project management
default_enabled: false
