---
name: github_import_gists
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107651
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386579
milestone: '15.8'
type: development
group: group::import
default_enabled: false
