---
name: gitlab_metrics_error_rate_sli
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103976
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/383071
milestone: '15.7'
type: development
group: group::scalability
default_enabled: false
