---
name: incident_event_tags
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107194
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/387647
milestone: '15.8'
type: development
group: group::respond
default_enabled: false
