---
name: mirror_only_branches_match_regex
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/99201
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381667
milestone: '15.6'
type: development
group: "group::source code"
default_enabled: false
