---
name: move_cancel_pending_pipelines_to_async
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106347
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385099
milestone: '15.9'
type: development
group: group::pipeline execution
default_enabled: false
