---
name: multiple_environment_approval_rules_fe
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105719
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/384334
milestone: '15.7'
type: development
group: group::release
default_enabled: false
