---
name: new_fonts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102347
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/379147
milestone: '15.7'
type: development
group: group::foundations
default_enabled: true
