---
name: on_demand_scans_runner_tags
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103634
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381910
milestone: '15.7'
type: development
group: group::dynamic analysis
default_enabled: false
