---
name: pipeline_schedules_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/99155
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/375139
milestone: '15.5'
type: development
group: group::pipeline execution
default_enabled: false
