---
name: project_runners_vue_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107646
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386573
milestone: '15.8'
type: development
group: group::runner
default_enabled: false
