---
name: project_statistics_bulk_increment
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103879
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385845
milestone: '15.7'
type: development
group: group::pipeline insights
default_enabled: false
