---
name: project_language_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104167
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385465
milestone: '15.7'
type: development
group: group::workspace
default_enabled: false
