---
name: remove_job_token_on_completion
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108021
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386871
milestone: '15.8'
type: development
group: group::pipeline execution
default_enabled: false
