---
name: route_hll_to_snowplow_phase4
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103528"
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/366767
milestone: '15.7'
type: development
group: group::product intelligence
default_enabled: false
