---
name: search_index_curation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98809
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/375274
milestone: '15.6'
type: development
group: group::global search
default_enabled: false
