---
name: service_desk_new_note_email_native_attachments
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107887
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/386860
milestone: '15.8'
type: development
group: group::respond
default_enabled: false
