---
name: stop_stale_environments
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108616
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/387820
milestone: '15.8'
type: development
group: group::release
default_enabled: false
