---
name: use_primary_and_secondary_stores_for_repository_cache
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107232#note_1216317991
rollout_issue_url:
milestone: '15.7'
type: development
group: group::scalability
default_enabled: false
