---
name: use_ref_type_parameter
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102936
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381501
milestone: '15.6'
type: development
group: group::source code
default_enabled: false

