---
name: your_work_sidebar
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107345
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385855
milestone: '15.8'
type: development
group: group::foundations
default_enabled: false
