---
name: all_commits_compliance_report
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/102364
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/388523
milestone: '15.9'
type: development
group: group::compliance
default_enabled: false
