---
name: arkose_labs_oauth_signup_challenge
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/107906
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/388033
milestone: '15.9'
type: development
group: group::anti-abuse
default_enabled: false
