---
name: cube_api_proxy
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96250
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/385600
milestone: '15.4'
type: development
group: group::product analytics
default_enabled: false
