---
name: ensure_onboarding
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98031
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/382219
milestone: '15.7'
type: development
group: group::acquisition
default_enabled: false
