---
name: free_user_cap_new_namespaces
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/99131
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/352633
milestone: '15.5'
type: development
group: group::acquisition
default_enabled: false
