---
name: identity_verification_credit_card
introduced_by_url: 'https://gitlab.com/gitlab-org/gitlab/-/merge_requests/99202'
rollout_issue_url: 'https://gitlab.com/gitlab-org/gitlab/-/issues/375675'
milestone: '15.5'
type: development
group: group::anti-abuse
default_enabled: false
