---
name: product_analytics_internal_preview
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98610
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/376347
milestone: '15.5'
type: development
group: group::product analytics
default_enabled: false
