---
name: refactor_vulnerability_filters
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/103113
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/381638
milestone: '15.6'
type: development
group: group::threat insights
default_enabled: false
