---
name: remove_non_gma_memberships
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27581
rollout_issue_url:
milestone: '12.10'
type: development
group: group::authentication and authorization
default_enabled: false
