---
name: search_issue_label_aggregation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97804
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/374604
milestone: '15.5'
type: development
group: group::global search
default_enabled: false
