---
name: search_code_with_zoekt
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/105049
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/388519
milestone: '15.9'
type: development
group: group::global search
default_enabled: false
