---
name: sec_mark_dropped_findings_as_resolved
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95422
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/375128
milestone: '15.5'
type: development
group: group::static analysis
default_enabled: false
