---
description: Mirrored Redis source_code_pushes events sent to Snowplow
category: PostReceive
action: push
identifiers:
  - project
  - user
  - namespace
product_section: dev
product_stage: create
product_group: source_code
product_category: source_code_management
milestone: "15.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104670
distributions:
  - ce
  - ee
tiers:
  - free
  - premium
  - ultimate
