---
description: Count of unique merge requests created per month
category: Gitlab::UsageDataCounters::MergeRequestActivityUniqueCounter
action: create
label_description: "Mirrored RedisHLL i_code_review_user_create_mr_monthly events sent to Snowplow"
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- project
- user
- namespace
product_section: dev
product_stage: create
product_group: code_review
product_category: code_review
milestone: "15.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106869
distributions:
- ce
- ee
tiers: 
- free
- premium
- ultimate

