---
data_category: optional
key_path: counts.snippet_create
description: Count of newly created Snippets
product_section: dev
product_stage: create
product_group: editor
product_category: snippets
value_type: number
status: active
time_frame: all
data_source: redis
instrumentation_class: RedisMetric
options:
  prefix: snippet
  event: create
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
milestone: "<13.9"
