---
data_category: optional
key_path: counts_weekly.aggregated_metrics.code_review_extension_category_monthly_active_users
description: Number of users performing code review extension_category events
product_section: dev
product_stage: create
product_group: code_review
product_category:
value_type: number
status: active
milestone: "13.12"
introduced_by_url:
time_frame: 7d
instrumentation_class: AggregatedMetric
data_source: redis_hll
options:
  aggregate:
    operator: OR
    attribute: user_id
  events:
    - 'i_code_review_user_vs_code_api_request'
    - 'i_code_review_user_jetbrains_api_request'
    - 'i_code_review_user_gitlab_cli_api_request'
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
