---
data_category: optional
key_path: counts_monthly.aggregated_metrics.code_review_extension_category_monthly_active_users
description: Number of users performing i_code_review_user_vs_code_api_request event
product_section: dev
product_stage: create
product_group: code_review
product_category:
value_type: number
status: active
milestone: "13.12"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53553
time_frame: 28d
instrumentation_class: AggregatedMetric
data_source: redis_hll
options:
  aggregate:
    operator: OR
    attribute: user_id
  events:
    - 'i_code_review_user_vs_code_api_request'
    - 'i_code_review_user_jetbrains_api_request'
    - 'i_code_review_user_gitlab_cli_api_request'
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
performance_indicator_type: []
