---
key_path: redis_hll_counters.issues_edit.g_project_management_issue_design_comments_removed_monthly
description: Count of unique users per month who removed a comment on a design
product_section: dev
product_stage: plan
product_group: product_planning
product_category: design_management
value_type: number
status: active
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108307
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
performance_indicator_type: []
options:
  events:
    - g_project_management_issue_design_comments_removed
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
