---
data_category: optional
key_path: redis_hll_counters.testing.i_testing_active_user_monthly
description: Count of monthly active users for pipeline insights features
product_section: ops
product_stage: verify
product_group: pipeline_insights
product_category: testing
value_type: number
status: active
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108629
time_frame: 28d
instrumentation_class: AggregatedMetric
data_source: redis_hll
options:
  aggregate:
    operator: OR
    attribute: user_id
  events:
    - 'i_testing_test_report_uploaded'
    - 'i_testing_coverage_report_uploaded'
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
