---
name: search_curation_dry_run
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104321
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/383003
milestone: '15.7'
type: ops
group: group::global search
default_enabled: true
