---
name: search_index_curation_main_index
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/104423
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/383106
milestone: '15.7'
type: ops
group: group::global search
default_enabled: false
