---
name: sidekiq_memory_killer_read_only_mode
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98519
milestone: '15.5'
type: ops
group: group::application performance
default_enabled: false
