---
data_category: operational
key_path: usage_activity_by_stage.secure.container_scanning_scans
description: Counts container scanning jobs
product_section: sec
product_stage: secure
product_group: composition_analysis
product_category: container_scanning
value_type: number
status: active
time_frame: all
data_source: database
distribution:
- ee
tier:
- ultimate
- premium
- free
performance_indicator_type: []
milestone: "<13.9"
